services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: construtech-app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
      - /var/www/vendor
    networks:
      - construtech-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: construtech-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: construtech
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - construtech-network

volumes:
  mysql_data:

networks:
  construtech-network:
    driver: bridge
